/**
 * Auth service — real backend implementation.
 *
 * INTEGRATION NOTE: every exported name, signature and return shape is
 * unchanged from the previous mock version, so no page or component needed
 * editing. `AuthResult`, `VerificationResult`, `signIn`, `register`,
 * `sendVerificationCode`, `verifyCode`, `updateUserProfile`, `getAllUsers`
 * and `getUserById` all behave as before from the caller's point of view.
 *
 * The one thing worth understanding: Forum.tsx, Profile.tsx and
 * QuestionThread.tsx call `getUserById()` SYNCHRONOUSLY while rendering, so
 * it cannot become an async call without changing those components. Instead
 * a module-level user cache is kept, and `cacheUsers()` is called by the
 * forum service whenever a response arrives with authors embedded (the
 * backend embeds them for exactly this reason). `getUserById` then answers
 * from that cache, as it previously answered from MOCK_USERS.
 */
import type { User, RegisterFormData } from '../types';
import { api, errorMessage } from './api';

export interface AuthResult {
  success: boolean;
  user?: User;
  error?: string;
}

export interface VerificationResult {
  success: boolean;
  message: string;
}

// ── Synchronous user cache (see note above) ─────────────────────────────
const userCache = new Map<string, User>();

export function cacheUsers(users: (User | undefined | null)[]): void {
  for (const u of users) {
    if (u && u.id) userCache.set(u.id, u);
  }
}

export function getUserById(id: string): User | undefined {
  return userCache.get(id);
}

export function getAllUsers(): User[] {
  return Array.from(userCache.values());
}

/** Warms the cache for authors not yet seen. Fire-and-forget. */
export async function prefetchUsers(ids: string[]): Promise<void> {
  const missing = Array.from(new Set(ids.filter(id => id && !userCache.has(id))));
  if (missing.length === 0) return;
  try {
    const users = await api.get<User[]>(`/users?ids=${encodeURIComponent(missing.join(','))}`);
    cacheUsers(users);
  } catch {
    // A cold cache only means initials render in place of a name; it is not
    // worth failing the page over.
  }
}

// ── Session ─────────────────────────────────────────────────────────────

interface AuthEnvelope {
  user: User;
}

export async function signIn(identifier: string, password: string): Promise<AuthResult> {
  try {
    const { user } = await api.post<AuthEnvelope>('/auth/login', { identifier, password });
    cacheUsers([user]);
    return { success: true, user };
  } catch (error) {
    return { success: false, error: errorMessage(error, 'Sign-in failed.') };
  }
}

export async function register(data: RegisterFormData): Promise<AuthResult> {
  try {
    // The username is generated by the backend from the full name; it is not
    // sent, and the returned user carries the generated value.
    const { user } = await api.post<AuthEnvelope>('/auth/register', {
      fullName: data.fullName,
      phone: data.phone,
      email: data.email,
      accountType: data.accountType,
      password: data.password,
      confirmPassword: data.confirmPassword,
      course: data.course,
      department: data.department,
    });
    cacheUsers([user]);
    return { success: true, user };
  } catch (error) {
    return { success: false, error: errorMessage(error, 'Registration failed.') };
  }
}

/** Restores the session from the httpOnly cookie on page load. */
export async function getCurrentUser(): Promise<User | null> {
  try {
    const { user } = await api.get<AuthEnvelope>('/auth/me');
    cacheUsers([user]);
    return user;
  } catch {
    return null; // 401 simply means "not signed in".
  }
}

export async function signOut(): Promise<void> {
  try {
    await api.post('/auth/logout');
  } catch {
    // Clearing local state matters more than the round trip succeeding.
  }
}

// ── Verification ────────────────────────────────────────────────────────

export async function sendVerificationCode(email: string): Promise<VerificationResult> {
  try {
    return await api.post<VerificationResult>('/auth/verification/send', { email });
  } catch (error) {
    return { success: false, message: errorMessage(error, 'Could not send a verification code.') };
  }
}

export async function verifyCode(userId: string, code: string): Promise<VerificationResult> {
  try {
    return await api.post<VerificationResult>('/auth/verification/confirm', { userId, code });
  } catch (error) {
    return { success: false, message: errorMessage(error, 'Verification failed.') };
  }
}

// ── Password reset ──────────────────────────────────────────────────────

export async function requestPasswordReset(email: string): Promise<VerificationResult> {
  try {
    return await api.post<VerificationResult>('/auth/password-reset/request', { email });
  } catch (error) {
    return { success: false, message: errorMessage(error, 'Could not start a password reset.') };
  }
}

export async function confirmPasswordReset(
  token: string,
  newPassword: string,
): Promise<VerificationResult> {
  try {
    return await api.post<VerificationResult>('/auth/password-reset/confirm', { token, newPassword });
  } catch (error) {
    return { success: false, message: errorMessage(error, 'Could not reset the password.') };
  }
}

// ── Profile ─────────────────────────────────────────────────────────────

export async function updateUserProfile(
  userId: string,
  updates: Partial<User>,
): Promise<AuthResult> {
  try {
    // The backend resolves the target from the auth cookie via /users/me and
    // accepts only editable fields, so `userId` is no longer what decides
    // whose profile changes. The parameter is kept so Profile.tsx needs no
    // edit; it is intentionally unused.
    void userId;
    const user = await api.patch<User>('/users/me', {
      bio: updates.bio,
      course: updates.course,
      department: updates.department,
      avatarColor: updates.avatarColor,
    });
    cacheUsers([user]);
    return { success: true, user };
  } catch (error) {
    return { success: false, error: errorMessage(error, 'Could not update your profile.') };
  }
}

/** Fetches a profile by id, for the profile page. */
export async function fetchUserById(id: string): Promise<User | undefined> {
  try {
    const user = await api.get<User>(`/users/${encodeURIComponent(id)}`);
    cacheUsers([user]);
    return user;
  } catch {
    return undefined;
  }
}
